export const optimizedAssetMap: Record<string, string> = {
  "/assets/b-system-objective.png": "/assets-optimized/b-system-objective.webp",
  "/assets/figma/1.png": "/assets-optimized/figma/1.webp",
  "/assets/figma/10.png": "/assets-optimized/figma/10.webp",
  "/assets/figma/2.png": "/assets-optimized/figma/2.webp",
  "/assets/figma/3.png": "/assets-optimized/figma/3.webp",
  "/assets/figma/4.png": "/assets-optimized/figma/4.webp",
  "/assets/figma/5.5.png": "/assets-optimized/figma/5.5.webp",
  "/assets/figma/5.png": "/assets-optimized/figma/5.webp",
  "/assets/figma/6.png": "/assets-optimized/figma/6.webp",
  "/assets/figma/7.png": "/assets-optimized/figma/7.webp",
  "/assets/figma/8.png": "/assets-optimized/figma/8.webp",
  "/assets/figma/9.png": "/assets-optimized/figma/9.webp",
  "/assets/figma-dev/b-system/design-spec-frame.png": "/assets-optimized/figma-dev/b-system/design-spec-frame.webp",
  "/assets/figma-dev/b-system/product-objectives-frame.png": "/assets-optimized/figma-dev/b-system/product-objectives-frame.webp",
  "/assets/figma-dev/b-system/product-objectives.png": "/assets-optimized/figma-dev/b-system/product-objectives.webp",
  "/assets/figma-dev/b-system/project-cards.png": "/assets-optimized/figma-dev/b-system/project-cards.webp",
  "/assets/figma-dev/b-system/requirement-frame.png": "/assets-optimized/figma-dev/b-system/requirement-frame.webp",
  "/assets/figma-dev/dashboard-clip-left.png": "/assets-optimized/figma-dev/dashboard-clip-left.webp",
  "/assets/figma-dev/dashboard-clip-right.png": "/assets-optimized/figma-dev/dashboard-clip-right.webp",
  "/assets/figma-dev/dashboard-layer-1.png": "/assets-optimized/figma-dev/dashboard-layer-1.webp",
  "/assets/figma-dev/dashboard-vector-bg.png": "/assets-optimized/figma-dev/dashboard-vector-bg.webp",
  "/assets/figma-dev/home/img41.png": "/assets-optimized/figma-dev/home/img41.webp",
  "/assets/figma-dev/web-xinxin-bg-bottom.png": "/assets-optimized/figma-dev/web-xinxin-bg-bottom.webp",
  "/assets/figma-dev/web-xinxin-bg-main.png": "/assets-optimized/figma-dev/web-xinxin-bg-main.webp",
  "/assets/slices/123_拷贝.png": "/assets-optimized/slices/123_拷贝.webp",
  "/assets/slices/123_拷贝_1.png": "/assets-optimized/slices/123_拷贝_1.webp",
  "/assets/slices/1_310053792.png": "/assets-optimized/slices/1_310053792.webp",
  "/assets/slices/2_26.png": "/assets-optimized/slices/2_26.webp",
  "/assets/slices/3213.png": "/assets-optimized/slices/3213.webp",
  "/assets/slices/3213_4.png": "/assets-optimized/slices/3213_4.webp",
  "/assets/slices/Desktop_-_3_1.png": "/assets-optimized/slices/Desktop_-_3_1.webp",
  "/assets/slices/Desktop_-_5_1.png": "/assets-optimized/slices/Desktop_-_5_1.webp",
  "/assets/slices/Dim_Light_MacBook_Mockup_1.png": "/assets-optimized/slices/Dim_Light_MacBook_Mockup_1.webp",
  "/assets/slices/duanwu-sothis-2026.png": "/assets-optimized/slices/duanwu-sothis-2026.webp",
  "/assets/slices/Ellipse 1049.png": "/assets-optimized/slices/Ellipse 1049.webp",
  "/assets/slices/Ellipse 1050.png": "/assets-optimized/slices/Ellipse 1050.webp",
  "/assets/slices/Ellipse 1051.png": "/assets-optimized/slices/Ellipse 1051.webp",
  "/assets/slices/Ellipse 1053.png": "/assets-optimized/slices/Ellipse 1053.webp",
  "/assets/slices/Ellipse 1054.png": "/assets-optimized/slices/Ellipse 1054.webp",
  "/assets/slices/Ellipse 1055.png": "/assets-optimized/slices/Ellipse 1055.webp",
  "/assets/slices/Ellipse 1056.png": "/assets-optimized/slices/Ellipse 1056.webp",
  "/assets/slices/Ellipse 1057.png": "/assets-optimized/slices/Ellipse 1057.webp",
  "/assets/slices/Ellipse 1058.png": "/assets-optimized/slices/Ellipse 1058.webp",
  "/assets/slices/fanbaba_A_picture_of_a_traditional_Chinese_festival_a_little_bo_c_upscayl_4x_realesrgan-x4plus_1_1.png": "/assets-optimized/slices/fanbaba_A_picture_of_a_traditional_Chinese_festival_a_little_bo_c_upscayl_4x_realesrgan-x4plus_1_1.webp",
  "/assets/slices/FireShot_Capture_011_-_青岛信芯微电子科技股份有限公司-信芯微官网_-_www.hi-image.cn.png": "/assets-optimized/slices/FireShot_Capture_011_-_青岛信芯微电子科技股份有限公司-信芯微官网_-_www.hi-image.cn.webp",
  "/assets/slices/FireShot_Capture_012_-_关于信芯微_-_信芯微电子科技有限公司_-_www.hi-image.cn.png": "/assets-optimized/slices/FireShot_Capture_012_-_关于信芯微_-_信芯微电子科技有限公司_-_www.hi-image.cn.webp",
  "/assets/slices/FireShot_Capture_014_-_行业新闻_-_信芯微电子科技有限公司_-_www.hi-image.cn.png": "/assets-optimized/slices/FireShot_Capture_014_-_行业新闻_-_信芯微电子科技有限公司_-_www.hi-image.cn.webp",
  "/assets/slices/Frame_1940698324.png": "/assets-optimized/slices/Frame_1940698324.webp",
  "/assets/slices/Group 1940698317.png": "/assets-optimized/slices/Group 1940698317.webp",
  "/assets/slices/Group 1940698322.png": "/assets-optimized/slices/Group 1940698322.webp",
  "/assets/slices/group-1940698317.png": "/assets-optimized/slices/group-1940698317.webp",
  "/assets/slices/Group_208.png": "/assets-optimized/slices/Group_208.webp",
  "/assets/slices/Group_210.png": "/assets-optimized/slices/Group_210.webp",
  "/assets/slices/Group_211_1.png": "/assets-optimized/slices/Group_211_1.webp",
  "/assets/slices/Image0001_1.png": "/assets-optimized/slices/Image0001_1.webp",
  "/assets/slices/image_1.png": "/assets-optimized/slices/image_1.webp",
  "/assets/slices/image_2.png": "/assets-optimized/slices/image_2.webp",
  "/assets/slices/jimeng-2025-09-28-2879-把右下角绿色的字抠出来放到黑背景上面_1.png": "/assets-optimized/slices/jimeng-2025-09-28-2879-把右下角绿色的字抠出来放到黑背景上面_1.webp",
  "/assets/slices/logo5_1.png": "/assets-optimized/slices/logo5_1.webp",
  "/assets/slices/Macbook_1.png": "/assets-optimized/slices/Macbook_1.webp",
  "/assets/slices/Mask group.png": "/assets-optimized/slices/Mask group.webp",
  "/assets/slices/Snipaste_2025-10-13_14-47-39.png": "/assets-optimized/slices/Snipaste_2025-10-13_14-47-39.webp",
  "/assets/slices/Snipaste_2025-10-13_14-48-35.png": "/assets-optimized/slices/Snipaste_2025-10-13_14-48-35.webp",
  "/assets/slices/Snipaste_2025-10-13_14-48-50.png": "/assets-optimized/slices/Snipaste_2025-10-13_14-48-50.webp",
  "/assets/slices/Snipaste_2025-10-13_14-49-01.png": "/assets-optimized/slices/Snipaste_2025-10-13_14-49-01.webp",
  "/assets/slices/Snipaste_2025-10-13_17-11-06.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-11-06.webp",
  "/assets/slices/Snipaste_2025-10-13_17-11-41.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-11-41.webp",
  "/assets/slices/Snipaste_2025-10-13_17-11-54.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-11-54.webp",
  "/assets/slices/Snipaste_2025-10-13_17-12-11.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-12-11.webp",
  "/assets/slices/Snipaste_2025-10-13_17-12-27.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-12-27.webp",
  "/assets/slices/Snipaste_2025-10-13_17-12-43.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-12-43.webp",
  "/assets/slices/Snipaste_2025-10-13_17-13-03.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-13-03.webp",
  "/assets/slices/Snipaste_2025-10-13_17-13-51.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-13-51.webp",
  "/assets/slices/Snipaste_2025-10-13_17-14-29.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-14-29.webp",
  "/assets/slices/Snipaste_2025-10-13_17-15-10.png": "/assets-optimized/slices/Snipaste_2025-10-13_17-15-10.webp",
  "/assets/slices/wifi.png": "/assets-optimized/slices/wifi.webp",
  "/assets/slices/中文版_1.png": "/assets-optimized/slices/中文版_1.webp",
  "/assets/slices/创_芯引领 智慧生活.png": "/assets-optimized/slices/创_芯引领 智慧生活.webp",
  "/assets/slices/图层_1.png": "/assets-optimized/slices/图层_1.webp",
  "/assets/slices/图层_10_1.png": "/assets-optimized/slices/图层_10_1.webp",
  "/assets/slices/图层_1_5.png": "/assets-optimized/slices/图层_1_5.webp",
  "/assets/slices/图层_1_拷贝_1.png": "/assets-optimized/slices/图层_1_拷贝_1.webp",
  "/assets/slices/图层_3.png": "/assets-optimized/slices/图层_3.webp",
  "/assets/slices/图层_4.png": "/assets-optimized/slices/图层_4.webp",
  "/assets/slices/图层_7.png": "/assets-optimized/slices/图层_7.webp",
  "/assets/slices/图层_8.png": "/assets-optimized/slices/图层_8.webp",
  "/assets/slices/图层_9.png": "/assets-optimized/slices/图层_9.webp",
  "/assets/slices/图层_9_拷贝.png": "/assets-optimized/slices/图层_9_拷贝.webp",
  "/assets/slices/图片4_1.png": "/assets-optimized/slices/图片4_1.webp",
  "/assets/slices/图片5_1.png": "/assets-optimized/slices/图片5_1.webp",
  "/assets/slices/图片扩图_1.png": "/assets-optimized/slices/图片扩图_1.webp",
  "/assets/slices/圆角矩形_2.png": "/assets-optimized/slices/圆角矩形_2.webp",
  "/assets/slices/地图.png": "/assets-optimized/slices/地图.webp",
  "/assets/slices/地图_拷贝.png": "/assets-optimized/slices/地图_拷贝.webp",
  "/assets/slices/椭圆_5.png": "/assets-optimized/slices/椭圆_5.webp",
  "/assets/slices/椭圆_5_拷贝.png": "/assets-optimized/slices/椭圆_5_拷贝.webp",
  "/assets/slices/椭圆_5_拷贝_2.png": "/assets-optimized/slices/椭圆_5_拷贝_2.webp",
  "/assets/slices/椭圆_5_拷贝_3.png": "/assets-optimized/slices/椭圆_5_拷贝_3.webp",
  "/assets/slices/椭圆_5_拷贝_4.png": "/assets-optimized/slices/椭圆_5_拷贝_4.webp",
  "/assets/slices/注射.png": "/assets-optimized/slices/注射.webp",
  "/assets/slices/画板_1_3.png": "/assets-optimized/slices/画板_1_3.webp",
  "/assets/slices/组_1.png": "/assets-optimized/slices/组_1.webp",
  "/assets/slices/记忆.png": "/assets-optimized/slices/记忆.webp",
  "/assets/slices/资源_1_2.png": "/assets-optimized/slices/资源_1_2.webp",
  "/assets/slices/首页.png": "/assets-optimized/slices/首页.webp"
};
